package config

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
)

const rcloneConfTemplate = `# Auto-generated by immichto115 — DO NOT EDIT MANUALLY

[webdav115]
type = webdav
url = {{ .WebDAV.URL }}
user = {{ .WebDAV.User }}
pass = {{ .WebDAVObscuredPass }}
vendor = {{ .WebDAV.Vendor }}
{{ if .Encrypt.Enabled }}
[crypt115]
type = crypt
remote = webdav115:{{ .Backup.RemoteDir }}
password = {{ .CryptObscuredPass }}
{{ if .CryptObscuredSalt }}password2 = {{ .CryptObscuredSalt }}
{{ end }}filename_encryption = standard
directory_name_encryption = true
{{ end }}`

type rcloneConfData struct {
	WebDAV             WebDAVConfig
	Backup             BackupConfig
	Encrypt            EncryptConfig
	WebDAVObscuredPass string
	CryptObscuredPass  string
	CryptObscuredSalt  string
}

// GenerateRcloneConf 根据当前配置生成临时 rclone.conf 文件。
// 返回文件路径。调用者负责使用 CleanupRcloneConf 清理。
func GenerateRcloneConf(cfg AppConfig) (string, error) {
	tmpDir, err := os.MkdirTemp("", "immichto115-rclone-*")
	if err != nil {
		return "", fmt.Errorf("failed to create temp dir: %w", err)
	}

	confPath := filepath.Join(tmpDir, "rclone.conf")

	webdavPass, err := ObscurePassword(cfg.WebDAV.Password)
	if err != nil {
		os.RemoveAll(tmpDir)
		return "", fmt.Errorf("failed to obscure webdav password: %w", err)
	}

	data := rcloneConfData{
		WebDAV:             cfg.WebDAV,
		Backup:             cfg.Backup,
		Encrypt:            cfg.Encrypt,
		WebDAVObscuredPass: webdavPass,
	}

	if cfg.Encrypt.Enabled && cfg.Encrypt.Password != "" {
		cryptPass, err := ObscurePassword(cfg.Encrypt.Password)
		if err != nil {
			os.RemoveAll(tmpDir)
			return "", fmt.Errorf("failed to obscure crypt password: %w", err)
		}
		data.CryptObscuredPass = cryptPass

		if cfg.Encrypt.Salt != "" {
			cryptSalt, err := ObscurePassword(cfg.Encrypt.Salt)
			if err != nil {
				os.RemoveAll(tmpDir)
				return "", fmt.Errorf("failed to obscure crypt salt: %w", err)
			}
			data.CryptObscuredSalt = cryptSalt
		}
	}

	tmpl, err := template.New("rclone.conf").Parse(rcloneConfTemplate)
	if err != nil {
		os.RemoveAll(tmpDir)
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	f, err := os.Create(confPath)
	if err != nil {
		os.RemoveAll(tmpDir)
		return "", fmt.Errorf("failed to create rclone.conf: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		os.RemoveAll(tmpDir)
		return "", fmt.Errorf("failed to render rclone.conf: %w", err)
	}

	return confPath, nil
}

// GetRemoteName 根据加密配置返回 Rclone 应使用的 remote 名称。
func GetRemoteName(cfg AppConfig) string {
	if cfg.Encrypt.Enabled {
		return "crypt115:"
	}
	return "webdav115:" + cfg.Backup.RemoteDir
}

// CleanupRcloneConf 删除临时 rclone.conf 及其父目录。
func CleanupRcloneConf(confPath string) {
	if confPath == "" {
		return
	}
	os.RemoveAll(filepath.Dir(confPath))
}

// ObscurePassword 使用 rclone obscure 命令将明文密码转为 Rclone 内部格式。
func ObscurePassword(plaintext string) (string, error) {
	if plaintext == "" {
		return "", nil
	}
	cmd := exec.Command("rclone", "obscure", plaintext)
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("rclone obscure failed: %w", err)
	}
	return strings.TrimSpace(string(out)), nil
}
