package config

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"strings"
	"text/template"
)

const rcloneConfTemplate = `# Auto-generated by immichto115 — DO NOT EDIT MANUALLY

[webdav115]
type = webdav
url = {{ .WebDAV.URL }}
user = {{ .WebDAV.User }}
pass = {{ .WebDAVObscuredPass }}
vendor = {{ .WebDAV.Vendor }}
{{ if .Encrypt.Enabled }}
[crypt115]
type = crypt
remote = webdav115:{{ .Backup.RemoteDir }}
password = {{ .CryptObscuredPass }}
{{ if .CryptObscuredSalt }}password2 = {{ .CryptObscuredSalt }}
{{ end }}filename_encryption = standard
directory_name_encryption = true
{{ end }}`

type rcloneConfData struct {
	WebDAV             WebDAVConfig
	Backup             BackupConfig
	Encrypt            EncryptConfig
	WebDAVObscuredPass string
	CryptObscuredPass  string
	CryptObscuredSalt  string
}

// GenerateRcloneConf 根据当前配置生成临时 rclone.conf 文件。
// 返回文件路径。调用者负责使用 CleanupRcloneConf 清理。
func GenerateRcloneConf(cfg AppConfig) (string, error) {
	tmpDir, err := os.MkdirTemp("", "immichto115-rclone-*")
	if err != nil {
		return "", fmt.Errorf("failed to create temp dir: %w", err)
	}

	confPath := filepath.Join(tmpDir, "rclone.conf")

	webdavPass, err := ObscurePassword(cfg.WebDAV.Password)
	if err != nil {
		os.RemoveAll(tmpDir)
		return "", fmt.Errorf("failed to obscure webdav password: %w", err)
	}

	data := rcloneConfData{
		WebDAV:             cfg.WebDAV,
		Backup:             cfg.Backup,
		Encrypt:            cfg.Encrypt,
		WebDAVObscuredPass: webdavPass,
	}

	if cfg.Encrypt.Enabled && cfg.Encrypt.Password != "" {
		cryptPass, err := ObscurePassword(cfg.Encrypt.Password)
		if err != nil {
			os.RemoveAll(tmpDir)
			return "", fmt.Errorf("failed to obscure crypt password: %w", err)
		}
		data.CryptObscuredPass = cryptPass

		if cfg.Encrypt.Salt != "" {
			cryptSalt, err := ObscurePassword(cfg.Encrypt.Salt)
			if err != nil {
				os.RemoveAll(tmpDir)
				return "", fmt.Errorf("failed to obscure crypt salt: %w", err)
			}
			data.CryptObscuredSalt = cryptSalt
		}
	}

	tmpl, err := template.New("rclone.conf").Parse(rcloneConfTemplate)
	if err != nil {
		os.RemoveAll(tmpDir)
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	f, err := os.Create(confPath)
	if err != nil {
		os.RemoveAll(tmpDir)
		return "", fmt.Errorf("failed to create rclone.conf: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		os.RemoveAll(tmpDir)
		return "", fmt.Errorf("failed to render rclone.conf: %w", err)
	}

	return confPath, nil
}

// GetRemoteName 根据加密配置返回 Rclone 应使用的 remote 名称。
func GetRemoteName(cfg AppConfig) string {
	if cfg.Encrypt.Enabled {
		return "crypt115:"
	}
	cleanRemoteDir := path.Clean("/" + strings.TrimSpace(cfg.Backup.RemoteDir))
	if cleanRemoteDir == "." || cleanRemoteDir == "" {
		cleanRemoteDir = "/"
	}
	return "webdav115:" + cleanRemoteDir
}

// BuildRemotePath 根据配置和请求路径拼出可用于 rclone 的完整远端路径。
func BuildRemotePath(cfg AppConfig, reqPath string) string {
	cleanPath := path.Clean("/" + strings.TrimSpace(reqPath))
	if cleanPath == "." || cleanPath == "" {
		cleanPath = "/"
	}

	if cfg.Encrypt.Enabled {
		if cleanPath == "/" {
			return "crypt115:"
		}
		return "crypt115:" + strings.TrimPrefix(cleanPath, "/")
	}

	remote := GetRemoteName(cfg)
	if cleanPath == "/" {
		return remote
	}
	if strings.HasSuffix(remote, "/") {
		return remote + strings.TrimPrefix(cleanPath, "/")
	}
	return remote + cleanPath
}

// CleanupRcloneConf 删除临时 rclone.conf 及其父目录。
func CleanupRcloneConf(confPath string) {
	if confPath == "" {
		return
	}
	os.RemoveAll(filepath.Dir(confPath))
}

// rcloneObscureKey is the fixed key used by rclone to obscure passwords.
// See: https://github.com/rclone/rclone/blob/master/fs/config/obscure/obscure.go
var rcloneObscureKey = []byte{
	0x9c, 0x93, 0x5b, 0x48, 0x73, 0x0a, 0x55, 0x4d,
	0x6b, 0xfd, 0x7c, 0x63, 0xc8, 0x86, 0xa9, 0x2b,
	0xd3, 0x90, 0x19, 0x8e, 0xb8, 0x12, 0x8a, 0xfb,
	0xf4, 0xde, 0x16, 0x2b, 0x8b, 0x95, 0xf6, 0x38,
}

// ObscurePassword 使用与 rclone obscure 相同的 AES-CTR 算法将明文密码转为 Rclone 内部格式。
// 不再需要外部 rclone 可执行文件。
func ObscurePassword(plaintext string) (string, error) {
	if plaintext == "" {
		return "", nil
	}

	block, err := aes.NewCipher(rcloneObscureKey)
	if err != nil {
		return "", fmt.Errorf("failed to create AES cipher: %w", err)
	}

	// rclone uses AES block size (16 bytes) as iv
	ciphertext := make([]byte, aes.BlockSize+len(plaintext))
	iv := ciphertext[:aes.BlockSize]
	if _, err := io.ReadFull(rand.Reader, iv); err != nil {
		return "", fmt.Errorf("failed to generate IV: %w", err)
	}

	stream := cipher.NewCTR(block, iv)
	stream.XORKeyStream(ciphertext[aes.BlockSize:], []byte(plaintext))

	return base64.RawURLEncoding.EncodeToString(ciphertext), nil
}
